/**
 * landingPageTemplates.ts
 * 
 * ⚠️ THIS FILE IS A STUB — All real generation is done by the backend AI service.
 * The function below is kept for type compatibility only. It is NOT used in the
 * actual page generation flow. Real pages are generated via pagesApi.create() →
 * backend aiService.generateLandingPageContent() with full uniqueness enforcement.
 */

export interface LandingPageConfig {
  businessName: string;
  industry: string;
  pageType: string;
  businessDesc: string;
  targetAudience: string;
  ctaText: string;
  aiPrompt: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  websiteUrl?: string;
  logoUrl?: string;
}

/**
 * @deprecated Not used. All generation happens via backend AI.
 * Kept only for TypeScript compatibility.
 */
export function generateLandingPageHtml(_cfg: LandingPageConfig): { html: string; css: string } {
  // This function is intentionally empty — it should never be called.
  // If you see this output, something is wrong with the generation pipeline.
  return {
    html: `<div style="padding:100px 20px;text-align:center;font-family:sans-serif;color:#64748b;">
      <h2>Page is being generated by AI...</h2>
      <p>If you see this, the AI backend is unavailable. Please try again.</p>
    </div>`,
    css: ''
  };
}
